# Must be copied to /etc/systemd/system/hostapd.service.d/override.con
# OVS -> hostapd -> DNSMasq must start in that order
# This file is a drop-in ovveride to ensure hostapd waits for OVS to start

[Unit]
After=ovs-vswitchd.service
Requires=ovs-vswitchd.service
